//! Generated via `helpers/gen_models.py`
//! Do not edit this file directly.
//! 
//! Defines models and model units available to a
//! user for manipulating `./notifications` values.

use serde::{Deserialize, Serialize};

use oxinat_derive::ModelProperty;
#[derive(Debug, Deserialize, Serialize)]
pub struct NotificationsProperty<T>(T);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "copyAdminOnNotifications")]
pub struct CopyAdminOnNotifications(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "copyAdminOnPageEmails")]
pub struct CopyAdminOnPageEmails(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailAllowNonuserSubscribers")]
pub struct EmailAllowNonuserSubscribers(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailMessageForgotPasswordReset")]
pub struct EmailMessageForgotPasswordReset(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailMessageForgotUsernameRequest")]
pub struct EmailMessageForgotUsernameRequest(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailMessageUserRegistration")]
pub struct EmailMessageUserRegistration(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailPrefix")]
pub struct EmailPrefix(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailRecipientErrorMessages")]
pub struct EmailRecipientErrorMessages(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailRecipientIssueReports")]
pub struct EmailRecipientIssueReports(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailRecipientNewUserAlert")]
pub struct EmailRecipientNewUserAlert(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "emailRecipientUpdate")]
pub struct EmailRecipientUpdate(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "helpContactInfo")]
pub struct HelpContactInfo(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "notifyAdminPipelineEmails")]
pub struct NotifyAdminPipelineEmails(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "notifyAdminProjectAccessRequest")]
pub struct NotifyAdminProjectAccessRequest(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "notifyAdminSessionTransfer")]
pub struct NotifyAdminSessionTransfer(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "notifyAdminUserRegistration")]
pub struct NotifyAdminUserRegistration(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpAuth")]
pub struct SmtpAuth(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpEnabled")]
pub struct SmtpEnabled(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpHostname")]
pub struct SmtpHostname(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpPassword")]
pub struct SmtpPassword(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpPort")]
pub struct SmtpPort(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpProtocol")]
pub struct SmtpProtocol(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpSslTrust")]
pub struct SmtpSslTrust(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpStartTls")]
pub struct SmtpStartTls(String);

#[derive(Debug, Serialize, ModelProperty)]
#[serde(rename = "smtpUsername")]
pub struct SmtpUsername(String);

#[derive(Debug, Deserialize, Serialize)]
pub struct Notifications {
    #[serde(rename = "copyAdminOnNotifications")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub copy_admin_on_notifications: Option<NotificationsProperty<CopyAdminOnNotifications>>,
    #[serde(rename = "copyAdminOnPageEmails")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub copy_admin_on_page_emails: Option<NotificationsProperty<CopyAdminOnPageEmails>>,
    #[serde(rename = "emailAllowNonuserSubscribers")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_allow_nonuser_subscribers: Option<NotificationsProperty<EmailAllowNonuserSubscribers>>,
    #[serde(rename = "emailMessageForgotPasswordReset")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_message_forgot_password_reset: Option<NotificationsProperty<EmailMessageForgotPasswordReset>>,
    #[serde(rename = "emailMessageForgotUsernameRequest")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_message_forgot_username_request: Option<NotificationsProperty<EmailMessageForgotUsernameRequest>>,
    #[serde(rename = "emailMessageUserRegistration")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_message_user_registration: Option<NotificationsProperty<EmailMessageUserRegistration>>,
    #[serde(rename = "emailPrefix")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_prefix: Option<NotificationsProperty<EmailPrefix>>,
    #[serde(rename = "emailRecipientErrorMessages")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_recipient_error_messages: Option<NotificationsProperty<EmailRecipientErrorMessages>>,
    #[serde(rename = "emailRecipientIssueReports")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_recipient_issue_reports: Option<NotificationsProperty<EmailRecipientIssueReports>>,
    #[serde(rename = "emailRecipientNewUserAlert")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_recipient_new_user_alert: Option<NotificationsProperty<EmailRecipientNewUserAlert>>,
    #[serde(rename = "emailRecipientUpdate")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub email_recipient_update: Option<NotificationsProperty<EmailRecipientUpdate>>,
    #[serde(rename = "helpContactInfo")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub help_contact_info: Option<NotificationsProperty<HelpContactInfo>>,
    #[serde(rename = "notifyAdminPipelineEmails")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub notify_admin_pipeline_emails: Option<NotificationsProperty<NotifyAdminPipelineEmails>>,
    #[serde(rename = "notifyAdminProjectAccessRequest")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub notify_admin_project_access_request: Option<NotificationsProperty<NotifyAdminProjectAccessRequest>>,
    #[serde(rename = "notifyAdminSessionTransfer")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub notify_admin_session_transfer: Option<NotificationsProperty<NotifyAdminSessionTransfer>>,
    #[serde(rename = "notifyAdminUserRegistration")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub notify_admin_user_registration: Option<NotificationsProperty<NotifyAdminUserRegistration>>,
    #[serde(rename = "smtpAuth")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_auth: Option<NotificationsProperty<SmtpAuth>>,
    #[serde(rename = "smtpEnabled")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_enabled: Option<NotificationsProperty<SmtpEnabled>>,
    #[serde(rename = "smtpHostname")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_hostname: Option<NotificationsProperty<SmtpHostname>>,
    #[serde(rename = "smtpPassword")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_password: Option<NotificationsProperty<SmtpPassword>>,
    #[serde(rename = "smtpPort")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_port: Option<NotificationsProperty<SmtpPort>>,
    #[serde(rename = "smtpProtocol")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_protocol: Option<NotificationsProperty<SmtpProtocol>>,
    #[serde(rename = "smtpSslTrust")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_ssl_trust: Option<NotificationsProperty<SmtpSslTrust>>,
    #[serde(rename = "smtpStartTls")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_start_tls: Option<NotificationsProperty<SmtpStartTls>>,
    #[serde(rename = "smtpUsername")]
     #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_username: Option<NotificationsProperty<SmtpUsername>>,
}

